name: deploy-api
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # required for OIDC
      contents: read
    env:
      AWS_REGION: us-east-1
      ECR_REPO: apdisc-api
      ECS_CLUSTER: apdisc-cluster
      ECS_SERVICE: apdisc-api-svc
      ACCOUNT_ID: 100024683059
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/apdisc-github-deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push :latest
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
          cd backend/api
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment


